services:
  database:
    image: postgres:17.2
    env_file:
      - database/.env
    ports:
      - "5432:5432"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data

  bot:
    build:
      dockerfile: Dockerfile
    env_file:
      - bot/.env
      - database/.env