services:
  database:
    image: postgres:17.2-alpine
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      - database
    volumes:
      - ./bot_logs.log:/bot_logs.log
    env_file:
      - .env
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: DockerfileAdmin
    container_name: fastapi-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"

