"""delete time_get_schedule

Revision ID: 2a68e2b2b0ec
Revises: 4d89bfb3b718
Create Date: 2024-12-10 15:13:14.800124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a68e2b2b0ec"
down_revision: Union[str, None] = "4d89bfb3b718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "time_get_schedule")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "time_get_schedule", postgresql.TIME(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
