"""0_1_0

Revision ID: 35aeb25461e8
Revises: 9f06d9026d4f
Create Date: 2024-12-29 17:49:58.846853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35aeb25461e8"
down_revision: Union[str, None] = "9f06d9026d4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages_to_admin",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("date_time", sa.DateTime(), nullable=True),
        sa.Column("messages", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("reminder", sa.Time(), nullable=True))
    op.drop_column("users", "status")
    op.drop_column("users", "substatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("substatus", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users", sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "reminder")
    op.drop_table("messages_to_admin")
    # ### end Alembic commands ###
