"""add formob in Group

Revision ID: 39c1753bd6a1
Revises: cda14aee6a66
Create Date: 2024-12-09 19:46:31.159613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39c1753bd6a1"
down_revision: Union[str, None] = "cda14aee6a66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("formob", sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "formob")
    # ### end Alembic commands ###
