"""add substatus, rename status

Revision ID: 4d89bfb3b718
Revises: 39c1753bd6a1
Create Date: 2024-12-09 22:38:07.877761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d89bfb3b718"
down_revision: Union[str, None] = "39c1753bd6a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("status", sa.String(), nullable=True))
    op.add_column("users", sa.Column("substatus", sa.String(), nullable=True))
    op.drop_column("users", "user_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("user_status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "substatus")
    op.drop_column("users", "status")
    # ### end Alembic commands ###
