"""Default None in gruppa

Revision ID: 64345600f3ae
Revises: f40438de2796
Create Date: 2024-12-06 03:25:56.712833

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64345600f3ae'
down_revision: Union[str, None] = 'f40438de2796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('kaf', sa.String(), nullable=True))
    op.drop_column('groups', 'сaf')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('сaf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('groups', 'kaf')
    # ### end Alembic commands ###
