"""add reminder

Revision ID: 97764943f19a
Revises: 9f06d9026d4f
Create Date: 2024-12-27 22:24:58.019717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97764943f19a"
down_revision: Union[str, None] = "9f06d9026d4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("reminder", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reminder")
    # ### end Alembic commands ###
