"""0.0.1

Revision ID: 9f06d9026d4f
Revises: 
Create Date: 2024-12-13 17:17:37.587376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f06d9026d4f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("caf", sa.String(), nullable=True),
        sa.Column("kyrs", sa.Integer(), nullable=True),
        sa.Column("formob", sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("para", sa.String(), nullable=True),
        sa.Column("lecture_time", sa.String(), nullable=True),
        sa.Column("audience", sa.String(), nullable=True),
        sa.Column("lesson", sa.String(), nullable=True),
        sa.Column("type_lesson", sa.String(), nullable=True),
        sa.Column("teacher_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("gruppa", sa.Integer(), nullable=True),
        sa.Column("formob", sa.String(length=1), nullable=True),
        sa.Column("kyrs", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("substatus", sa.String(), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gruppa"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("schedules")
    op.drop_table("groups")
    # ### end Alembic commands ###
