"""delete nullable=False

Revision ID: b78c5ac7cb98
Revises: 97779abdd3e7
Create Date: 2024-12-07 18:15:12.234841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b78c5ac7cb98"
down_revision: Union[str, None] = "97779abdd3e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "gruppa", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "users", "formob", existing_type=sa.VARCHAR(length=1), nullable=True
    )
    op.alter_column("users", "kyrs", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "kyrs", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "users", "formob", existing_type=sa.VARCHAR(length=1), nullable=False
    )
    op.alter_column("users", "gruppa", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
