"""add kyrs in Group

Revision ID: cda14aee6a66
Revises: 37556f83b6aa
Create Date: 2024-12-09 19:27:00.048846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cda14aee6a66"
down_revision: Union[str, None] = "37556f83b6aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("kyrs", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "kyrs")
    # ### end Alembic commands ###
