"""add schedule

Revision ID: ea05bc65624a
Revises: d1c2def2ce8b
Create Date: 2024-12-05 19:32:14.042455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea05bc65624a"
down_revision: Union[str, None] = "d1c2def2ce8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("para", sa.String(), nullable=True),
        sa.Column("lecture_time", sa.String(), nullable=True),
        sa.Column("audience", sa.String(), nullable=True),
        sa.Column("lesson", sa.String(), nullable=True),
        sa.Column("type_lesson", sa.String(), nullable=True),
        sa.Column("teacher_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedules")
    # ### end Alembic commands ###
