"""add kaf in group

Revision ID: f40438de2796
Revises: 82171e6d0610
Create Date: 2024-12-06 02:18:06.432082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40438de2796'
down_revision: Union[str, None] = '82171e6d0610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('сaf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'caf')
    # ### end Alembic commands ###
